version = 0.1
[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "aws-lambda-custom-docker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dakp13tc81dv"
s3_prefix = "aws-lambda-custom-docker"
region = "eu-central-1"
profile = "deepracer9"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"



[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ethan-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vf2349ffygur"
s3_prefix = "ethan-stack"
region = "ap-southeast-2"
profile = "deepracer9"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
